### ISSUE TITLE
Yiff.Party Hyrdus Downloader Not Working???

### ISSUE THREAD

**Issue by RichardLNewman** [CuddleBear92/Hydrus-Presets-and-Scripts#74] opened 2019-08-02 13:29 UTC
Using the latest Hydrus client and the downloaders simply don't work.  All of them are "connection failed" status.  Thanks!

**Comment by matjojo** [comment] 2019-08-02 15:15
if all downloaders are failing the problem is probably your internet connection?

**Comment by CuddleBear92** [comment] 2019-08-02 15:18
The parser works out of the box for all clients unless your are blocked from the site somehow.
The json api is still live and havent changed. Even the parser here is the default parser that comes with the client.

**Comment by CuddleBear92** [comment] 2019-08-02 15:45
That being said, the site is known to be slow and be down a ton. 
Closing the issue, really no need to have it. Should work must be on your side. Jump on discord for more direct help.

**Closed by CuddleBear92** 2019-08-02 15:45 UTC
